name: Deploy Three Spring Boot Applications with Java 21

on:
  push:
    branches:
      - main # Executa o workflow apenas na branch principal.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configuração inicial
      - name: Checkout Terraform repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Atualizado para Java 21

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and Deploy Producao Application
        run: |
          # Clonar o repositório
          git clone https://github.com/brunobucci/soat7grupo5-producao.git producao
          cd producao

          # Mudar para a branch develop
          git checkout test

          # Instalar dependências e executar testes com cobertura
          mvn clean verify
          coverage=$(mvn jacoco:report | grep -oP 'instructionCoverage\s*=\s*\K[0-9.]+')
          echo "Coverage for Producao: $coverage%"
          #if (( $(echo "$coverage < 80" | bc -l) )); then
          #  echo "Coverage for Producao is below 80%! Exiting."
          #  exit 1
          #fi

          # Build do artefato
          mvn clean package -DskipTests
          cd ..

          # Deploy para o EC2
          scp -o StrictHostKeyChecking=no -i "$AWS_PRIVATE_KEY" producao/target/*.jar ec2-user@${AWS_HOST_PRODUCAO}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i "$AWS_PRIVATE_KEY" ec2-user@${AWS_HOST_PRODUCAO} "sudo systemctl restart producao-app"
